name: npm audit

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  scan-frontend:
    name: npm audit frontend
    defaults:
      run:
        working-directory: ./packages/client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./packages/client

  scan-backend:
    name: npm audit backend
    defaults:
      run:
        working-directory: ./packages/server
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: install dependencies
          run: npm ci
        - uses: oke-py/npm-audit-action@v3
          with:
            audit_level: high
            github_token: ${{ secrets.GITHUB_TOKEN }}
            working_directory: ./packages/server
